# Generated by Django 6.1.1 on 2026-09-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="tipo_acervo",
            field=models.CharField(
                choices=[("digital", "Digital"), ("fisico", "Físico")],
                default="fisico",
                max_length=10,
            ),
        ),
    ]
